# Parametri configurazione SSL
# Crea una nuova chiave auto-firmata con:
#   keytool -genkeypair -keyalg RSA -alias selfsigned -keystore <name> -storepass <password> -validity 360 -keysize 2048
# Modifica poi i valori sottostanti
ssl:
  active: false
  password: "banlist"
  name: "key.jks"

# Percorsi in cui mostrare l'output
output:
  path:
    Ban: "/ban"
    Freeze: "/freeze"
    OnlinePlayers: "/online"
    OfflinePlayers: "/offline"
    essentials:
      Mute: "/mute"
      Jail: "/jail"
    vault:
      Permissions: "/permissions"
      Economy: "/economy"
  port: 80

# Cosa devo mostrare?
show:
  OnlinePlayers: true
  OfflinePlayers: true
  Ban: true
  Freeze: true
  essentials:
    Mute: true
    Jail: true
  vault:
    Permissions: true
    Economy: true
